// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUOyZYP4PyeMDP7zvZ4WmkFg7UKVcid6k',
    appId: '1:569484613588:android:25b02d6f38d7bac06da841',
    messagingSenderId: '569484613588',
    projectId: 'brandy-9aa6a',
    databaseURL: 'https://brandy-9aa6a-default-rtdb.firebaseio.com',
    storageBucket: 'brandy-9aa6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2xhoNm9SepFsgMmPNvcWc58G6J1vfqZ4',
    appId: '1:569484613588:ios:68a0d2c184e678a56da841',
    messagingSenderId: '569484613588',
    projectId: 'brandy-9aa6a',
    databaseURL: 'https://brandy-9aa6a-default-rtdb.firebaseio.com',
    storageBucket: 'brandy-9aa6a.firebasestorage.app',
    iosBundleId: 'com.linkdevelopment.brandyUser',
  );

}